language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
    - php: 7.3

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "vendor"

install:
  - composer install

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
