language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
  - php: 7.3
    env: REPORT=acquia.yml
  - php: 7.3
    env: REPORT=lightning.yml

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "vendor"

before_script:
  # Additional PHP config
  - phpenv config-add travis.php.ini

install:
  - composer install

script:
  - composer test
  - ./bin/evaluate create-report $REPORT --format=yaml
